/*************************************************
Initially Generated by SSoT.me - 2017
    EJ Alexandra - ssotme odxml42/odxml-to-csharp-pocos
    This file WILL NOT be overwritten once changes are made.
*************************************************/
using System;
using System.ComponentModel;
                        
namespace adventofcode.Lib.DataClasses
{                   
    
    public partial class QuantityOfMass 
    {
        public QuantityOfMass()
        {
            this.InitPoco();
        }

        public QuantityOfMass(int mass)
            : this()
        {
            this.CalculateFuel(mass);
        }

        private void CalculateFuel(int mass)
        {
            this.Mass = mass;

            this.FuelRequired = (int)(Math.Floor(this.Mass.Value / 3.0) - 2);

            var fueldMassFuel = 0;

            if (this.FuelRequired > 0)
            {
                var fueldMass = new QuantityOfMass(this.FuelRequired.Value);
                if (fueldMass.FinalFuelRequired > 0)
                {
                    fueldMassFuel = fueldMass.FinalFuelRequired.Value;
                }
            } 

            this.FinalFuelRequired = this.FuelRequired + fueldMassFuel;            
        }
    }
}